### ISSUE TITLE
Reconfigure Travis notifcations to slack instead of emailing Chris

### ISSUE THREAD

**Issue by chutsu** [wavelab/libwave#90]
At current whenever a branch fails or gets fixed @chutsu gets notified. This issue aims to

- Remove Chris from travis notications
- Redirect travis notifications to slack

**Comment by leokoppel** [comment]
It would be nice to limit this so it doesn't show build failures on topic branches on slack. Ideally it would notify only for "cron" builds, so we have an alert if master is not building due to some changed depedency.

Unfortunately there's no way to limit it to a specific branch through travis.yml: https://github.com/travis-ci/travis-ci/issues/1405

Maybe:
 - disable notifications
 - use a separate slack channel?

**Comment by chutsu** [comment]
Actually I'm for disabling notifications actually
